/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as RoomSlugIdRouteImport } from './routes/room.$slug.$id'

const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSlugIdRoute = RoomSlugIdRouteImport.update({
  id: '/room/$slug/$id',
  path: '/room/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/matches': typeof MatchesRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/room/$slug/$id': typeof RoomSlugIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/matches': typeof MatchesRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/room/$slug/$id': typeof RoomSlugIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/matches': typeof MatchesRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/room/$slug/$id': typeof RoomSlugIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/matches'
    | '/pricing'
    | '/profile'
    | '/safety'
    | '/rooms/$slug'
    | '/room/$slug/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/matches'
    | '/pricing'
    | '/profile'
    | '/safety'
    | '/rooms/$slug'
    | '/room/$slug/$id'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/matches'
    | '/pricing'
    | '/profile'
    | '/safety'
    | '/rooms/$slug'
    | '/room/$slug/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  MatchesRoute: typeof MatchesRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  SafetyRoute: typeof SafetyRoute
  RoomsSlugRoute: typeof RoomsSlugRoute
  RoomSlugIdRoute: typeof RoomSlugIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$slug/$id': {
      id: '/room/$slug/$id'
      path: '/room/$slug/$id'
      fullPath: '/room/$slug/$id'
      preLoaderRoute: typeof RoomSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  MatchesRoute: MatchesRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  SafetyRoute: SafetyRoute,
  RoomsSlugRoute: RoomsSlugRoute,
  RoomSlugIdRoute: RoomSlugIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
