/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as RoomSlugIdRouteImport } from './routes/room.$slug.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSlugIdRoute = RoomSlugIdRouteImport.update({
  id: '/room/$slug/$id',
  path: '/room/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/room/$slug/$id': typeof RoomSlugIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/room/$slug/$id': typeof RoomSlugIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/room/$slug/$id': typeof RoomSlugIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rooms/$slug' | '/room/$slug/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rooms/$slug' | '/room/$slug/$id'
  id: '__root__' | '/' | '/rooms/$slug' | '/room/$slug/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomsSlugRoute: typeof RoomsSlugRoute
  RoomSlugIdRoute: typeof RoomSlugIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$slug/$id': {
      id: '/room/$slug/$id'
      path: '/room/$slug/$id'
      fullPath: '/room/$slug/$id'
      preLoaderRoute: typeof RoomSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomsSlugRoute: RoomsSlugRoute,
  RoomSlugIdRoute: RoomSlugIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
